### CTC에 대해 이해해보자

참고  
 - https://soyoung-new-challenge.tistory.com/16
 - https://pytorch.org/docs/stable/generated/torch.nn.CTCLoss.html

In [134]:
import torch
import torch.nn as nn
import numpy as np


#### pytorch 구현

In [153]:
# Target are to be padded
T = 50      # Input sequence length
C = 3      # Number of classes (including blank)
N = 1      # Batch size
S = 30      # Target sequence length of longest target in batch (padding length)
S_min = 10  # Minimum target length, for demonstration purposes


np.random.seed(1024)
torch.manual_seed(1024)

# Initialize random batch of input vectors, for *size = (T,N,C)
input = torch.randn(T, N, C).log_softmax(2).detach().requires_grad_()

# Initialize random batch of targets (0 = blank, 1:C = classes)
target = torch.randint(low=1, high=C, size=(N, S), dtype=torch.long)

input_lengths = torch.full(size=(N,), fill_value=T, dtype=torch.long)
target_lengths = torch.randint(low=S_min, high=S, size=(N,), dtype=torch.long)

ctc_loss = nn.CTCLoss()

loss = ctc_loss(input, target, input_lengths, target_lengths)
loss.backward()



In [154]:
loss

tensor(1.0881, grad_fn=<MeanBackward0>)

In [127]:
input[0]

tensor([[[-2.8080, -0.3348, -1.4953]],

        [[-0.5556, -1.4950, -1.5993]],

        [[-0.9156, -3.1059, -0.5889]],

        [[-0.4529, -2.3207, -1.3242]],

        [[-2.8181, -0.4581, -1.1783]],

        [[-2.2224, -1.7191, -0.3391]],

        [[-0.8193, -0.6682, -3.0652]],

        [[-0.4027, -1.3488, -2.6320]],

        [[-2.3040, -1.2437, -0.4913]],

        [[-2.3654, -0.2028, -2.4121]],

        [[-1.1498, -0.9967, -1.1576]],

        [[-2.0130, -3.5465, -0.1772]],

        [[-1.9206, -0.2549, -2.5451]],

        [[-1.2941, -0.6312, -1.6403]],

        [[-0.8396, -0.9154, -1.7853]],

        [[-0.7194, -1.6334, -1.1467]],

        [[-2.5202, -2.3025, -0.1990]],

        [[-1.8897, -3.7202, -0.1928]],

        [[-0.2389, -3.1922, -1.7638]],

        [[-2.2546, -1.9363, -0.2865]],

        [[-2.2127, -0.2246, -2.3886]],

        [[-0.9989, -0.9290, -1.4406]],

        [[-1.8058, -0.2940, -2.4038]],

        [[-0.7381, -1.5695, -1.1589]],

        [[-1.9406, -0.3612, -1.8354]],



#### numpy 구현

In [116]:
def ctc_loss(input, target, input_lengths, target_lengths):
    
    

SyntaxError: invalid syntax (<ipython-input-116-39bed19c0620>, line 1)

In [117]:
input

tensor([[[-5.1742, -2.7009, -3.8615,  ..., -2.4767, -2.5400, -2.3888],
         [-4.2138, -2.5591, -3.5052,  ..., -2.6491, -4.9394, -4.2734],
         [-3.6041, -4.6131, -3.3184,  ..., -4.4636, -4.1453, -2.4955],
         ...,
         [-4.1359, -4.4425, -2.3024,  ..., -3.6499, -2.2589, -4.6180],
         [-4.1185, -3.7921, -4.4777,  ..., -3.2859, -3.6459, -2.7787],
         [-2.8012, -4.9705, -4.1716,  ..., -3.2638, -3.3255, -3.2514]],

        [[-4.4965, -2.3514, -2.3050,  ..., -1.3952, -5.1375, -3.5065],
         [-3.6705, -3.0324, -4.2171,  ..., -3.2088, -2.8633, -3.2155],
         [-3.8655, -4.5287, -3.5688,  ..., -3.6183, -2.0179, -3.4740],
         ...,
         [-3.0962, -2.7695, -3.4769,  ..., -4.5202, -2.3117, -3.7282],
         [-4.1606, -3.3555, -4.7161,  ..., -3.9148, -3.6422, -3.0812],
         [-4.2014, -5.0428, -3.1782,  ..., -4.5292, -2.3751, -4.0333]],

        [[-2.4319, -4.1464, -2.3097,  ..., -2.7401, -3.0508, -3.3365],
         [-4.0345, -3.7555, -2.7250,  ..., -3

In [118]:
target

tensor([[ 5,  5,  6, 16, 16, 18, 18,  6,  2,  4, 18, 15, 14, 19, 11,  4, 19,  8,
         15, 16, 18,  9,  7,  3,  6,  7,  5, 16, 13,  2],
        [14, 19, 15,  4,  8, 17,  4,  5,  1,  9, 10,  6, 18,  5,  9, 13, 17,  9,
          2, 15, 19,  7,  7, 17, 16,  4, 15, 12, 11,  5],
        [ 7,  9,  6, 17, 12, 14,  1, 12, 17, 11, 18,  6,  7, 16,  7,  5,  5,  7,
         15, 13, 10,  1, 12, 18,  7, 14, 17,  4,  2,  2],
        [ 5,  5,  8, 17, 14, 18,  8, 16, 15, 12,  4,  6,  4, 14, 16, 13,  5, 17,
         18,  7, 10,  9, 19,  3,  8,  6,  4,  9, 17, 12],
        [ 2, 11, 13,  8, 16, 10, 13, 12,  1,  4, 17, 12,  7, 17, 12,  8,  7, 11,
          3,  6, 16,  5, 11,  1, 16,  7, 10,  4, 14,  3],
        [ 3,  1,  1,  1, 13, 14,  6, 16, 15, 15,  8, 15,  9,  2,  2,  2, 19,  1,
         15,  1, 19, 10,  1,  8, 18,  4, 10,  6,  8, 15],
        [ 1,  6,  7, 18,  1,  1, 19, 11,  2, 17,  2,  5,  8,  3,  2,  4, 17, 12,
         14, 14, 14,  7,  9, 13, 16, 14,  2,  5, 14, 18],
        [15, 14, 13, 16, 19